// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace org.apache.flume.source.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class AvroFlumeEvent : ISpecificRecord
	{
		private static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"AvroFlumeEvent\",\"namespace\":\"org.apache.flume.source.avr" +
				"o\",\"fields\":[{\"name\":\"headers\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":" +
				"\"body\",\"type\":\"bytes\"}]}");
		private IDictionary<string,System.String> _headers;
		private byte[] _body;
		public virtual Schema Schema
		{
			get
			{
				return AvroFlumeEvent._SCHEMA;
			}
		}
		public IDictionary<string,System.String> headers
		{
			get
			{
				return this._headers;
			}
			set
			{
				this._headers = value;
			}
		}
		public byte[] body
		{
			get
			{
				return this._body;
			}
			set
			{
				this._body = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.headers;
			case 1: return this.body;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.headers = (IDictionary<string,System.String>)fieldValue; break;
			case 1: this.body = (System.Byte[])fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
