/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace DotNetFlumeNG.Client.Thrift
{
    public enum Status
    {
        OK = 0,
        FAILED = 1,
        ERROR = 2,
        UNKNOWN = 3,
    }
}
